all:
  children:
    ilo:
      hosts:
        srv01-ilo:
          ansible_host: 10.10.10.11
        srv02-ilo:
          ansible_host: 10.10.10.12

    lab:
      hosts:
        srv01-os:
          ansible_host: 192.168.10.11
          os_role: "k8s-node"
        srv02-os:
          ansible_host: 192.168.10.12
          os_role: "vmware-esxi"

    prod:
      hosts:
        prod-db-01:
          ansible_host: 172.16.20.21
          os_role: "db"
