env_name: "lab"
ilo_timezone: "UTC"
ilo_dns_servers:
  - 192.168.0.10
  - 192.168.0.11
ilo_ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org

firmware_expected:
  bios: "U32 v2.10"
  ilo: "2.85"
  storage: "5.04"
